version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./:/app
    command: "ng serve --host=0.0.0.0"
    ports:
      - "4200:4200"

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl/:/etc/ssl/
      - ./nginx/conf/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./dist/portfolio/browser/:/var/www/html/portfolio/current:rwx
