version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "4200:4200"

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/ssl/
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
