- name: Install certbot
  snap:
    name: certbot
    classic: true
    state: present

- name: Get SSL certificate via certbot standalone
  command: >
    certbot certonly --standalone
    --preferred-challenges http
    --email {{ support_email }}
    --agree-tos
    --no-eff-email
    -d {{ dns }}
  args:
    creates: "{{ certificate_path }}"

- name: Create certificate renew file
  copy:
    src: templates/certificate_renew_mail.txt.j2
    dest: "{{ certificate_mail_path }}"

- name: Create renew task with certbot
  cron:
    name: "Renouvellement Let's Encrypt avec Certbot (standalone)"
    job: >
      certbot renew --quiet
      --post-hook "{{ certbot_standalone_post_hook_script }}"
    month: 2
    user: root
  when: certbot_auto_renew
