- name: Init deployment folders
  hosts: all
  roles:
    - init
  tags:
    - init

- name: Build project
  hosts: localhost
  roles:
    - build
  tags:
    - build

- name: Archive project build
  hosts: localhost
  roles:
    - archive
  tags:
    - archive

- name: Copy archive on server
  hosts: all
  roles:
    - copy_archive
  tags:
    - copy_archive

- name: Unarchive build on server
  hosts: all
  roles:
    - unarchive
  tags:
    - unarchive

- name: Setup Nginx configuration
  hosts: barah
  roles:
    - nginx
  tags:
    - nginx
