- name: Init deployment folders
  hosts: barah
  roles:
    - init
  tags:
    - init

- name: Build project
  hosts: localhost
  roles:
    - build
  tags:
    - build

- name: Archive project build
  hosts: localhost
  roles:
    - archive
  tags:
    - archive

- name: Copy archive on server
  hosts: barah
  roles:
    - copy_archive
  tags:
    - copy_archive

- name: Create SSL/TLS certificate
  hosts: barah
  roles:
    - https
  tags:
    - https

- name: Deploy application
  hosts: barah
  gather_facts: false
  tasks:
    - block:
        - name: Unarchive build on server
          import_role:
            name: unarchive
          tags: unarchive

        - name: Setup Nginx configuration
          import_role:
            name: nginx
          tags: nginx

      rescue:
        - name: Rollback to previous release
          import_role:
            name: rollback
          tags: rollback
