name: Integration

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262