# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    
    - name: Build for production
      run: npm run build:prod

    - name: upload dist as artficat
      uses: actions/upload-artifact@v4.4.3
      with:
        name: dist
        path: dist


  deploy:
    name: deploy app
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artificat
      uses: actions/download-artifact@v4.1.8
      with:
        name: dist
        path: dist

    - name: List dist directory file
      run: ls -l dist/
  
